# -*- coding: utf-8 -*-
"""SEG Fabric Backlit Media Display.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H4vXEWTJSxzbjLBVFcuLGqhnaneOtOCx

## SEG Fabric Backlit Media Display Analysis--- EDA
"""

# import the libraries for the eda
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

df=pd.read_excel(r"/content/SEG Fabric Backlit Media Displays Clean data .xlsx")

# Fetching the data
df

# shape of the dataset
print(df.shape)

# checking the null values
df.isnull().sum()

# checking the data type of the data
df.info()

# Checking the columns
df.columns

# check the whole data set
df.describe(include='all')

# checking the null percentage
(df.isnull().sum() / len(df)) * 100

# visualization of Null Values by which Dimnesion
plt.figure(figsize=(8, 5))

sns.heatmap(df.isnull(), cbar=False)

plt.title("Missing Values")
plt.show()

#checking the Duplicate Values
df.duplicated().sum()

# checking the duplicate Rows
df[df.duplicated()]

# Top 15 Products
plt.figure(figsize=(10, 6))

df['Product Name '].value_counts().head(15).plot(kind="bar")

plt.title("Top 15 Products by Number of Listings")
plt.xlabel("Product Name")
plt.ylabel("Count")
plt.xticks(rotation=90)
plt.show()

"""# Numerical Analyszis

"""

df["Price "].dtype

df["Price "] = pd.to_numeric(df["Price "], errors="coerce")

df["Price "].describe()

df.nsmallest(10, "Price ")[["Product Name ", "Dimension", "Price "]]

df.nlargest(10, "Price ")[["Product Name ", "Dimension", "Price "]]

# Price & frequency Distribution
plt.figure(figsize=(10, 6))

sns.histplot(df["Price "], bins=15, kde=True)

plt.title("Price Distribution")
plt.xlabel("Price")
plt.ylabel("Frequency")

plt.show()

plt.figure(figsize=(8, 5))

sns.boxplot(x=df["Price "])

plt.title("Price Boxplot")
plt.xlabel("Price")

plt.show()

# checking the outlier with the help of IQT method
Q1 = df["Price "].quantile(0.25)
Q3 = df["Price "].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

outliers = df[
    (df["Price "] < lower_bound) |
    (df["Price "] > upper_bound)
]

outliers

product_price = (
    df.groupby("Product Name ")["Price "]
    .agg(["count", "mean", "min", "max"])
    .sort_values("mean", ascending=False)
)

product_price

plt.figure(figsize=(12, 7))

product_price["mean"].head(10).sort_values().plot(kind="barh")

plt.title("Top 10 Products by Average Price")
plt.xlabel("Average Price")
plt.ylabel("Product")

plt.show()

product_summary = df.groupby("Product Name ").agg(
    Number_of_Products=("Price ", "count"),
    Average_Price=("Price ", "mean"),
    Minimum_Price=("Price ", "min"),
    Maximum_Price=("Price ", "max")
)

product_summary.sort_values(
    "Average_Price",
    ascending=False
)

df["Dimension"].isnull().sum()

df["Dimension"].nunique()

df["Dimension"].value_counts().head(15)

df["Width"] = df["Dimension"].str.extract(
    r'(\d+(?:\.\d+)?)m\s*W',
    expand=False
).astype(float)

df["Height"] = df["Dimension"].str.extract(
    r'(\d+(?:\.\d+)?)m\s*H',
    expand=False
).astype(float)

df[["Dimension", "Width", "Height"]].head(15)

df["Area"] = df["Width"] * df["Height"]

df[["Product Name ", "Dimension", "Width", "Height", "Area", "Price "]]

area_data = df.dropna(subset=["Area", "Price "])

plt.figure(figsize=(10, 6))

sns.scatterplot(
    data=area_data,
    x="Area",
    y="Price "
)

plt.title("Relationship Between Display Area and Price")
plt.xlabel("Area (m²)")
plt.ylabel("Price ")

plt.show()

area_data[["Area", "Price "]].corr()

plt.figure(figsize=(14, 8))

sns.boxplot(
    data=df,
    x="Product Name ",
    y="Price "
)

plt.title("Price Distribution by Product")
plt.xticks(rotation=90)
plt.tight_layout()

plt.show()

top_products = df["Product Name "].value_counts().head(10).index

temp = df[df["Product Name "].isin(top_products)]

plt.figure(figsize=(14, 7))

sns.boxplot(
    data=temp,
    x="Product Name ",
    y="Price "
)

plt.xticks(rotation=90)
plt.title("Price Distribution of Top 10 Products")

plt.tight_layout()
plt.show()

numeric_cols = ["Width", "Height", "Area", "Price "]

plt.figure(figsize=(8, 6))

sns.heatmap(
    df[numeric_cols].corr(),
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Correlation Heatmap")

plt.show()

"""Summary of the Analysis

* The dataset contains **46 products** with three main variables: **Product Name, Dimension, and Price**.
* The **Price** of products varies significantly, ranging from approximately **25,915 to 1,245,600**.
* Most products are priced in the **lower-to-mid price range**, while a few **SEG Modular Lightbox Display Kits** have considerably higher prices.
* **SEG Modular Lightbox Display Kit** has the highest-priced products, with some models exceeding **₹1 million**.
* Several products have **missing Dimension values**, so the dimension data requires cleaning before detailed size-based analysis.
* Product names are repeated for different models or dimensions, making **product-wise price comparison** useful.
* The dataset contains different types of dimensions, such as **width/height measurements, depth measurements, and model numbers**, indicating inconsistent formatting.
* The price distribution is likely **right-skewed** because of the few very high-priced products.
* The high-priced modular lightbox models can be treated as potential **price outliers**, but they should not automatically be removed because they may represent genuinely premium products.
* Extracting **Width, Height, and Area** from the dimension column can help analyze whether larger displays generally have higher prices.
* Overall, the dataset can be used to understand **product pricing, price variation, product categories, dimensions, and the relationship between display size and price**.





"""

