# -*- coding: utf-8 -*-
"""Shell Scheme Exhibition Graphics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10HuIkmQooFZK9gq0_3_cn0UQVnHe2cOO
"""

# import the libraries for the eda
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

df=pd.read_excel("/content/Ptice details Shell Scheme.xlsx")

df

print(df.shape)

df.info()

df.isnull().sum()

df.columns

df.describe(include='all')

# Complete duplicate rows
print("Complete duplicate rows:", df.duplicated().sum())

# Duplicate SKU + Country combinations
print("Duplicate SKU-Country combinations:",
      df.duplicated(subset=['SKU', 'Country']).sum())

df.groupby('SKU')['Country'].nunique()

print("Unique Products:", df['Product Name'].nunique())
print("Unique SKUs:", df['SKU'].nunique())
print("Unique Countries:", df['Country'].nunique())
print("Unique Currencies:", df['Currency'].nunique())

df['Country'].value_counts()

df['Currency'].value_counts()

df['SKU'].value_counts()

country_stats = df.groupby('Country')['Amount'].agg(
    ['count', 'min', 'max', 'mean', 'median']
)

country_stats

sku_country_price = df.pivot(
    index='SKU',
    columns='Country',
    values='Amount'
)

sku_country_price

plt.figure(figsize=(12, 6))

sns.lineplot(
    data=df,
    x='SKU',
    y='Amount',
    hue='Country',
    marker='o'
)

plt.title('Price Trend by SKU and Country')
plt.xlabel('SKU')
plt.ylabel('Price')
plt.xticks(rotation=45)
plt.legend(title='Country')
plt.tight_layout()
plt.show()

countries = df['Country'].unique()

for country in countries:

    temp = df[df['Country'] == country]

    plt.figure(figsize=(10, 5))

    sns.barplot(
        data=temp,
        x='SKU',
        y='Amount'
    )

    plt.title(f'Product Pricing - {country}')
    plt.xlabel('SKU')
    plt.ylabel(f"Price ({temp['Currency'].iloc[0]})")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

df['Price_Change'] = df.groupby('Country')['Amount'].diff()

df[['Country', 'SKU', 'Amount', 'Price_Change']]

df['Price_Change_%'] = (
    df.groupby('Country')['Amount']
      .pct_change() * 100
)

df[['Country', 'SKU', 'Amount', 'Price_Change', 'Price_Change_%']]

df[['Amount']].corr()

df.groupby(['SKU', 'Country'])['Amount'].nunique()

df.groupby('Country')['Currency'].nunique()

"""Key Insights from EDA

Dataset size: The dataset contains 24 records, 6 unique SKUs, and 4 countries.

No missing values: All five columns have complete data, so there are no missing-value issues.

No duplicate records: Each SKU–Country combination is unique, giving 6 products across each of the 4 markets.

Consistent currency mapping:
USA → USD
UK → GBP
Australia → AUD
India → INR

Price increases with product size: Across all four countries, prices generally increase as the product dimensions increase.

The SS-EG-20X10 SKU has the highest listed price in every market.
SS-FULL is the lowest-priced SKU: SS-FULL has the lowest listed price in each country.

Country comparison needs currency conversion: Raw prices cannot be directly compared because each country uses a different currency.

A common currency should be used for meaningful international price comparison.

Strong pricing structure: The dataset shows a clear relationship between larger product size → higher price, which can be useful for pricing and product strategy.
"""

